### ISSUE TITLE
No suitable version of LLVM was found system-wide or pointed        to by LLVM_SYS_100_PREFIX.

### ISSUE THREAD

**Issue by noahsalvadordenjo** [ehsanmok/create-your-own-lang-with-rust#5]
After installling llvm with the following oneliner ```bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"```
I still have the following error
```
No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_100_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-100.2.1/src/lib.rs:483:1
    |
483 | / std::compile_error!(concat!(
484 | |       "No suitable version of LLVM was found system-wide or pointed
485 | |        to by LLVM_SYS_", env!("CARGO_PKG_VERSION_MAJOR"), "_PREFIX.
486 | |
...   |
490 | |        llvm-sys: https://crates.io/crates/llvm-sys
491 | |        llvmenv: https://crates.io/crates/llvmenv"));
    | |____________________________________________________^

error: No suitable version of LLVM was found system-wide or pointed
       to by LLVM_SYS_110_PREFIX.

       Consider using `llvmenv` to compile an appropriate copy of LLVM, and
       refer to the llvm-sys documentation for more information.

       llvm-sys: https://crates.io/crates/llvm-sys
       llvmenv: https://crates.io/crates/llvmenv
   --> /home/noone/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-110.0.1/src/lib.rs:486:1
    |
486 | / std::compile_error!(concat!(
487 | |     "No suitable version of LLVM was found system-wide or pointed
488 | |        to by LLVM_SYS_",
489 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
496 | |        llvmenv: https://crates.io/crates/llvmenv"
497 | | ));
    | |___^

error: aborting due to previous error

error: could not compile `llvm-sys`
```

**Comment by ehsanmok** [comment]
What do you get when you run `llvm-config --version` in terminal? you might have already some other versions of llvm installed so may need to change their precedence (assign the highest value for llvm 10 relative to others), for example with `sudo apt-get update alternatives` on Linux or its equivalent through Homebrew in Mac.

**Comment by ehsanmok** [comment]
Closing for no activity. Reopen if necessary.

**Comment by Nafi-Amaan-Hossain** [comment]
> `cargo clean` and rerun to see if it helps. Also what do you get when you run `llvm-config --version` in terminal? you might have already some other versions of llvm installed so may need to change their precedence (assign the highest value for llvm 10 relative to others), for example with `sudo apt-get update alternatives` on Linux or its equivalent through Homebrew in Mac.
I encountered this issue, and it compiles fine after a clean build with `cargo`.

**Comment by balanceglove2** [comment]
Worked for me after running `cargo clean`. Thanks @ehsanmok

**Comment by mayank-pathakk** [comment]
Thanks @ehsanmok , I was able to solve my issue after running `cargo clean`, can you please explain what this command does and how does it solves the issue ? 
Thanks in advance :)

**Comment by ehsanmok** [comment]
In Rustlang, `cargo clean` cleans up the previous build artifacts. So if you've build issues esp. when linking to other FFIs (here's is LLVM) then cleaning up and building again normally resolves such issues. It's the equivalent of restarting your computer :)

**Comment by omac777** [comment]
I just came across this project and decided to build it/test it on Fedora Silverblue.

I also encountered this error "No suitable version of LLVM was found".
By default llvm-config is not installed when you install llvm/lld.

In fedora silverblue, dnf isn't accessible directly.  I need to enter the toolbox and then discover the package holding llvm-config. **dnf provides** is very useful.  After doing so, it tells me it's in llvm-devel.
```
toolbox enter
dnf provides llvm-config
exit
```

Ok so let's install the llvm-devel package the Fedora Silverblue way:
```
sudo rpm-ostree install llvm lld llvm-devel
```

Done.  Now let's try all this again. Yes it's successful.

```
git clone https://github.com/ehsanmok/create-your-own-lang-with-rust
cd create-your-own-lang-with-rust/
source ~/.cargo/env 
cargo +nightly build
cargo +nightly test --tests --release
```

**Comment by re-masashi** [comment]
For some systems where LLVM cannot be found despite it being present (I encountered this issue a few days ago), you can use the --features=llvm-sys/prefer-dynamic
eg: 
```
cargo run --features=llvm-sys/prefer-dynamic
```

**Comment by aetilley** [comment]
I *do* have LLVM config and I still have this error.

`arthurtilley@Arthurs-MacBook-Pro-5 cool_rust % which llvm-config
/opt/homebrew/opt/llvm/bin/llvm-config
arthurtilley@Arthurs-MacBook-Pro-5 cool_rust % llvm-config --version
19.1.7
arthurtilley@Arthurs-MacBook-Pro-5 cool_rust % echo $LLVM_SYS_201_PREFIX                     
/opt/homebrew/opt/llvm
arthurtilley@Arthurs-MacBook-Pro-5 cool_rust % cargo check                                   
    Checking llvm-sys v201.0.0
error: No suitable version of LLVM was found system-wide or pointed
              to by LLVM_SYS_201_PREFIX.
       
              Consider using `llvmenv` to compile an appropriate copy of LLVM, and
              refer to the llvm-sys documentation for more information.
       
              llvm-sys: https://crates.io/crates/llvm-sys
              llvmenv: https://crates.io/crates/llvmenv
   --> /Users/arthurtilley/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/llvm-sys-201.0.0/src/lib.rs:533:1
    |
533 | / std::compile_error!(concat!(
534 | |     "No suitable version of LLVM was found system-wide or pointed
535 | |        to by LLVM_SYS_",
536 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
543 | |        llvmenv: https://crates.io/crates/llvmenv"
544 | | ));
    | |__^

error: could not compile `llvm-sys` (lib) due to 1 previous error
arthurtilley@Arthurs-MacBook-Pro-5 cool_rust % 
`

**Comment by PranavVerma-droid** [comment]
Hi, for anyone coming across this issue now and is running on Github Actions using Windows Latest, I recommend this Prebuild Binary that I compiled and uploaded on my own (v17.0.6).
Basically I was using `llvm-sys` with Windows Latest, and I tried for 1 month and I could not get it to work. All the Pre-Build Binaries did not include `llvm-config.exe` which is required for llvm-sys.

Here is the Repo: https://github.com/Delta-Engine/llvm-builds-windows/tree/main
